apiVersion: v1
kind: Service
metadata:
  name: crawl4ai-service
  namespace: {{ .Values.namespace }}
spec:
  selector: { app: crawl4ai-service }
  ports:
    - name: http
      port: 5003
      targetPort: 5003
  type: ClusterIP
