apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: {{ .Values.namespace }}
data:
{{- range $key, $value := .Values.apiGateway.config }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
