apiVersion: v1
kind: Secret
metadata:
  name: redis
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  REDIS_PASSWORD: {{ required "redis.password is required" .Values.redis.password | quote }}
