// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: proto/model/model.proto

package modelpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ModelService_ListProviders_FullMethodName       = "/model.ModelService/ListProviders"
	ModelService_CreateProvider_FullMethodName      = "/model.ModelService/CreateProvider"
	ModelService_UpdateProvider_FullMethodName      = "/model.ModelService/UpdateProvider"
	ModelService_DeleteProvider_FullMethodName      = "/model.ModelService/DeleteProvider"
	ModelService_SetProviderActive_FullMethodName   = "/model.ModelService/SetProviderActive"
	ModelService_ListModels_FullMethodName          = "/model.ModelService/ListModels"
	ModelService_CreateModel_FullMethodName         = "/model.ModelService/CreateModel"
	ModelService_UpdateModel_FullMethodName         = "/model.ModelService/UpdateModel"
	ModelService_DeleteModel_FullMethodName         = "/model.ModelService/DeleteModel"
	ModelService_SetModelActive_FullMethodName      = "/model.ModelService/SetModelActive"
	ModelService_ListUserProviders_FullMethodName   = "/model.ModelService/ListUserProviders"
	ModelService_CreateUserProvider_FullMethodName  = "/model.ModelService/CreateUserProvider"
	ModelService_UpdateUserProvider_FullMethodName  = "/model.ModelService/UpdateUserProvider"
	ModelService_DeleteUserProvider_FullMethodName  = "/model.ModelService/DeleteUserProvider"
	ModelService_ListUserModels_FullMethodName      = "/model.ModelService/ListUserModels"
	ModelService_CreateUserModel_FullMethodName     = "/model.ModelService/CreateUserModel"
	ModelService_UpdateUserModel_FullMethodName     = "/model.ModelService/UpdateUserModel"
	ModelService_DeleteUserModel_FullMethodName     = "/model.ModelService/DeleteUserModel"
	ModelService_ListAvailableModels_FullMethodName = "/model.ModelService/ListAvailableModels"
	ModelService_ListSettings_FullMethodName        = "/model.ModelService/ListSettings"
	ModelService_GetSetting_FullMethodName          = "/model.ModelService/GetSetting"
	ModelService_UpsertSetting_FullMethodName       = "/model.ModelService/UpsertSetting"
	ModelService_DeleteSetting_FullMethodName       = "/model.ModelService/DeleteSetting"
)

// ModelServiceClient is the client API for ModelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ModelService 系统配置域服务（config-service，gRPC 端口 5004）。
//
// 职责边界：只负责「模型目录 + 凭证 + 通用系统配置」的读写与加解密，
// 不负责调用上游大模型。将来生成服务需要模型时，作为本服务的 gRPC 客户端
// 取配置，HTTP 请求由它自己发。
//
// 密钥安全约定（契约层面强制）：
//   - 请求里的 api_key 是只写字段，服务端加密落库后不回显；
//   - 响应里只有 api_key_hint（末 4 位）与 api_key_updated_at，
//     供后台脱敏展示与轮换确认，没有任何字段能还原出完整密钥。
type ModelServiceClient interface {
	// ---- 平台渠道（管理端维护，平台提供的 base_url + api_key）----
	ListProviders(ctx context.Context, in *ListProvidersRequest, opts ...grpc.CallOption) (*ListProvidersResponse, error)
	CreateProvider(ctx context.Context, in *CreateProviderRequest, opts ...grpc.CallOption) (*ProviderInfo, error)
	UpdateProvider(ctx context.Context, in *UpdateProviderRequest, opts ...grpc.CallOption) (*ProviderInfo, error)
	DeleteProvider(ctx context.Context, in *DeleteProviderRequest, opts ...grpc.CallOption) (*DeleteProviderResponse, error)
	SetProviderActive(ctx context.Context, in *SetProviderActiveRequest, opts ...grpc.CallOption) (*ProviderInfo, error)
	// ---- 平台模型（挂在平台渠道下，用户端可见的主体）----
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error)
	CreateModel(ctx context.Context, in *CreateModelRequest, opts ...grpc.CallOption) (*ModelInfo, error)
	UpdateModel(ctx context.Context, in *UpdateModelRequest, opts ...grpc.CallOption) (*ModelInfo, error)
	DeleteModel(ctx context.Context, in *DeleteModelRequest, opts ...grpc.CallOption) (*DeleteModelResponse, error)
	SetModelActive(ctx context.Context, in *SetModelActiveRequest, opts ...grpc.CallOption) (*ModelInfo, error)
	// ---- 用户自定义渠道（用户自带 base_url + api_key）----
	ListUserProviders(ctx context.Context, in *ListUserProvidersRequest, opts ...grpc.CallOption) (*ListUserProvidersResponse, error)
	CreateUserProvider(ctx context.Context, in *CreateUserProviderRequest, opts ...grpc.CallOption) (*UserProviderInfo, error)
	UpdateUserProvider(ctx context.Context, in *UpdateUserProviderRequest, opts ...grpc.CallOption) (*UserProviderInfo, error)
	DeleteUserProvider(ctx context.Context, in *DeleteUserProviderRequest, opts ...grpc.CallOption) (*DeleteUserProviderResponse, error)
	// ---- 用户自选模型（挂在用户自定义渠道下，不计平台积分）----
	ListUserModels(ctx context.Context, in *ListUserModelsRequest, opts ...grpc.CallOption) (*ListUserModelsResponse, error)
	CreateUserModel(ctx context.Context, in *CreateUserModelRequest, opts ...grpc.CallOption) (*UserModelInfo, error)
	UpdateUserModel(ctx context.Context, in *UpdateUserModelRequest, opts ...grpc.CallOption) (*UserModelInfo, error)
	DeleteUserModel(ctx context.Context, in *DeleteUserModelRequest, opts ...grpc.CallOption) (*DeleteUserModelResponse, error)
	// ---- 用户端可用模型：平台模型 + 用户自定义模型的合并视图 ----
	ListAvailableModels(ctx context.Context, in *ListAvailableModelsRequest, opts ...grpc.CallOption) (*ListAvailableModelsResponse, error)
	// ---- 通用系统配置 ----
	ListSettings(ctx context.Context, in *ListSettingsRequest, opts ...grpc.CallOption) (*ListSettingsResponse, error)
	GetSetting(ctx context.Context, in *GetSettingRequest, opts ...grpc.CallOption) (*SettingInfo, error)
	UpsertSetting(ctx context.Context, in *UpsertSettingRequest, opts ...grpc.CallOption) (*SettingInfo, error)
	DeleteSetting(ctx context.Context, in *DeleteSettingRequest, opts ...grpc.CallOption) (*DeleteSettingResponse, error)
}

type modelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewModelServiceClient(cc grpc.ClientConnInterface) ModelServiceClient {
	return &modelServiceClient{cc}
}

func (c *modelServiceClient) ListProviders(ctx context.Context, in *ListProvidersRequest, opts ...grpc.CallOption) (*ListProvidersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProvidersResponse)
	err := c.cc.Invoke(ctx, ModelService_ListProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) CreateProvider(ctx context.Context, in *CreateProviderRequest, opts ...grpc.CallOption) (*ProviderInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProviderInfo)
	err := c.cc.Invoke(ctx, ModelService_CreateProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) UpdateProvider(ctx context.Context, in *UpdateProviderRequest, opts ...grpc.CallOption) (*ProviderInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProviderInfo)
	err := c.cc.Invoke(ctx, ModelService_UpdateProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) DeleteProvider(ctx context.Context, in *DeleteProviderRequest, opts ...grpc.CallOption) (*DeleteProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProviderResponse)
	err := c.cc.Invoke(ctx, ModelService_DeleteProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) SetProviderActive(ctx context.Context, in *SetProviderActiveRequest, opts ...grpc.CallOption) (*ProviderInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProviderInfo)
	err := c.cc.Invoke(ctx, ModelService_SetProviderActive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, ModelService_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) CreateModel(ctx context.Context, in *CreateModelRequest, opts ...grpc.CallOption) (*ModelInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelInfo)
	err := c.cc.Invoke(ctx, ModelService_CreateModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) UpdateModel(ctx context.Context, in *UpdateModelRequest, opts ...grpc.CallOption) (*ModelInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelInfo)
	err := c.cc.Invoke(ctx, ModelService_UpdateModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) DeleteModel(ctx context.Context, in *DeleteModelRequest, opts ...grpc.CallOption) (*DeleteModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteModelResponse)
	err := c.cc.Invoke(ctx, ModelService_DeleteModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) SetModelActive(ctx context.Context, in *SetModelActiveRequest, opts ...grpc.CallOption) (*ModelInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelInfo)
	err := c.cc.Invoke(ctx, ModelService_SetModelActive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) ListUserProviders(ctx context.Context, in *ListUserProvidersRequest, opts ...grpc.CallOption) (*ListUserProvidersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserProvidersResponse)
	err := c.cc.Invoke(ctx, ModelService_ListUserProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) CreateUserProvider(ctx context.Context, in *CreateUserProviderRequest, opts ...grpc.CallOption) (*UserProviderInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserProviderInfo)
	err := c.cc.Invoke(ctx, ModelService_CreateUserProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) UpdateUserProvider(ctx context.Context, in *UpdateUserProviderRequest, opts ...grpc.CallOption) (*UserProviderInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserProviderInfo)
	err := c.cc.Invoke(ctx, ModelService_UpdateUserProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) DeleteUserProvider(ctx context.Context, in *DeleteUserProviderRequest, opts ...grpc.CallOption) (*DeleteUserProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteUserProviderResponse)
	err := c.cc.Invoke(ctx, ModelService_DeleteUserProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) ListUserModels(ctx context.Context, in *ListUserModelsRequest, opts ...grpc.CallOption) (*ListUserModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserModelsResponse)
	err := c.cc.Invoke(ctx, ModelService_ListUserModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) CreateUserModel(ctx context.Context, in *CreateUserModelRequest, opts ...grpc.CallOption) (*UserModelInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserModelInfo)
	err := c.cc.Invoke(ctx, ModelService_CreateUserModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) UpdateUserModel(ctx context.Context, in *UpdateUserModelRequest, opts ...grpc.CallOption) (*UserModelInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserModelInfo)
	err := c.cc.Invoke(ctx, ModelService_UpdateUserModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) DeleteUserModel(ctx context.Context, in *DeleteUserModelRequest, opts ...grpc.CallOption) (*DeleteUserModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteUserModelResponse)
	err := c.cc.Invoke(ctx, ModelService_DeleteUserModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) ListAvailableModels(ctx context.Context, in *ListAvailableModelsRequest, opts ...grpc.CallOption) (*ListAvailableModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAvailableModelsResponse)
	err := c.cc.Invoke(ctx, ModelService_ListAvailableModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) ListSettings(ctx context.Context, in *ListSettingsRequest, opts ...grpc.CallOption) (*ListSettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSettingsResponse)
	err := c.cc.Invoke(ctx, ModelService_ListSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) GetSetting(ctx context.Context, in *GetSettingRequest, opts ...grpc.CallOption) (*SettingInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettingInfo)
	err := c.cc.Invoke(ctx, ModelService_GetSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) UpsertSetting(ctx context.Context, in *UpsertSettingRequest, opts ...grpc.CallOption) (*SettingInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettingInfo)
	err := c.cc.Invoke(ctx, ModelService_UpsertSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) DeleteSetting(ctx context.Context, in *DeleteSettingRequest, opts ...grpc.CallOption) (*DeleteSettingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSettingResponse)
	err := c.cc.Invoke(ctx, ModelService_DeleteSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModelServiceServer is the server API for ModelService service.
// All implementations must embed UnimplementedModelServiceServer
// for forward compatibility.
//
// ModelService 系统配置域服务（config-service，gRPC 端口 5004）。
//
// 职责边界：只负责「模型目录 + 凭证 + 通用系统配置」的读写与加解密，
// 不负责调用上游大模型。将来生成服务需要模型时，作为本服务的 gRPC 客户端
// 取配置，HTTP 请求由它自己发。
//
// 密钥安全约定（契约层面强制）：
//   - 请求里的 api_key 是只写字段，服务端加密落库后不回显；
//   - 响应里只有 api_key_hint（末 4 位）与 api_key_updated_at，
//     供后台脱敏展示与轮换确认，没有任何字段能还原出完整密钥。
type ModelServiceServer interface {
	// ---- 平台渠道（管理端维护，平台提供的 base_url + api_key）----
	ListProviders(context.Context, *ListProvidersRequest) (*ListProvidersResponse, error)
	CreateProvider(context.Context, *CreateProviderRequest) (*ProviderInfo, error)
	UpdateProvider(context.Context, *UpdateProviderRequest) (*ProviderInfo, error)
	DeleteProvider(context.Context, *DeleteProviderRequest) (*DeleteProviderResponse, error)
	SetProviderActive(context.Context, *SetProviderActiveRequest) (*ProviderInfo, error)
	// ---- 平台模型（挂在平台渠道下，用户端可见的主体）----
	ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
	CreateModel(context.Context, *CreateModelRequest) (*ModelInfo, error)
	UpdateModel(context.Context, *UpdateModelRequest) (*ModelInfo, error)
	DeleteModel(context.Context, *DeleteModelRequest) (*DeleteModelResponse, error)
	SetModelActive(context.Context, *SetModelActiveRequest) (*ModelInfo, error)
	// ---- 用户自定义渠道（用户自带 base_url + api_key）----
	ListUserProviders(context.Context, *ListUserProvidersRequest) (*ListUserProvidersResponse, error)
	CreateUserProvider(context.Context, *CreateUserProviderRequest) (*UserProviderInfo, error)
	UpdateUserProvider(context.Context, *UpdateUserProviderRequest) (*UserProviderInfo, error)
	DeleteUserProvider(context.Context, *DeleteUserProviderRequest) (*DeleteUserProviderResponse, error)
	// ---- 用户自选模型（挂在用户自定义渠道下，不计平台积分）----
	ListUserModels(context.Context, *ListUserModelsRequest) (*ListUserModelsResponse, error)
	CreateUserModel(context.Context, *CreateUserModelRequest) (*UserModelInfo, error)
	UpdateUserModel(context.Context, *UpdateUserModelRequest) (*UserModelInfo, error)
	DeleteUserModel(context.Context, *DeleteUserModelRequest) (*DeleteUserModelResponse, error)
	// ---- 用户端可用模型：平台模型 + 用户自定义模型的合并视图 ----
	ListAvailableModels(context.Context, *ListAvailableModelsRequest) (*ListAvailableModelsResponse, error)
	// ---- 通用系统配置 ----
	ListSettings(context.Context, *ListSettingsRequest) (*ListSettingsResponse, error)
	GetSetting(context.Context, *GetSettingRequest) (*SettingInfo, error)
	UpsertSetting(context.Context, *UpsertSettingRequest) (*SettingInfo, error)
	DeleteSetting(context.Context, *DeleteSettingRequest) (*DeleteSettingResponse, error)
	mustEmbedUnimplementedModelServiceServer()
}

// UnimplementedModelServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModelServiceServer struct{}

func (UnimplementedModelServiceServer) ListProviders(context.Context, *ListProvidersRequest) (*ListProvidersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProviders not implemented")
}
func (UnimplementedModelServiceServer) CreateProvider(context.Context, *CreateProviderRequest) (*ProviderInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProvider not implemented")
}
func (UnimplementedModelServiceServer) UpdateProvider(context.Context, *UpdateProviderRequest) (*ProviderInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProvider not implemented")
}
func (UnimplementedModelServiceServer) DeleteProvider(context.Context, *DeleteProviderRequest) (*DeleteProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteProvider not implemented")
}
func (UnimplementedModelServiceServer) SetProviderActive(context.Context, *SetProviderActiveRequest) (*ProviderInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method SetProviderActive not implemented")
}
func (UnimplementedModelServiceServer) ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedModelServiceServer) CreateModel(context.Context, *CreateModelRequest) (*ModelInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateModel not implemented")
}
func (UnimplementedModelServiceServer) UpdateModel(context.Context, *UpdateModelRequest) (*ModelInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateModel not implemented")
}
func (UnimplementedModelServiceServer) DeleteModel(context.Context, *DeleteModelRequest) (*DeleteModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteModel not implemented")
}
func (UnimplementedModelServiceServer) SetModelActive(context.Context, *SetModelActiveRequest) (*ModelInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method SetModelActive not implemented")
}
func (UnimplementedModelServiceServer) ListUserProviders(context.Context, *ListUserProvidersRequest) (*ListUserProvidersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUserProviders not implemented")
}
func (UnimplementedModelServiceServer) CreateUserProvider(context.Context, *CreateUserProviderRequest) (*UserProviderInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUserProvider not implemented")
}
func (UnimplementedModelServiceServer) UpdateUserProvider(context.Context, *UpdateUserProviderRequest) (*UserProviderInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserProvider not implemented")
}
func (UnimplementedModelServiceServer) DeleteUserProvider(context.Context, *DeleteUserProviderRequest) (*DeleteUserProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUserProvider not implemented")
}
func (UnimplementedModelServiceServer) ListUserModels(context.Context, *ListUserModelsRequest) (*ListUserModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUserModels not implemented")
}
func (UnimplementedModelServiceServer) CreateUserModel(context.Context, *CreateUserModelRequest) (*UserModelInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUserModel not implemented")
}
func (UnimplementedModelServiceServer) UpdateUserModel(context.Context, *UpdateUserModelRequest) (*UserModelInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserModel not implemented")
}
func (UnimplementedModelServiceServer) DeleteUserModel(context.Context, *DeleteUserModelRequest) (*DeleteUserModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUserModel not implemented")
}
func (UnimplementedModelServiceServer) ListAvailableModels(context.Context, *ListAvailableModelsRequest) (*ListAvailableModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAvailableModels not implemented")
}
func (UnimplementedModelServiceServer) ListSettings(context.Context, *ListSettingsRequest) (*ListSettingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSettings not implemented")
}
func (UnimplementedModelServiceServer) GetSetting(context.Context, *GetSettingRequest) (*SettingInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSetting not implemented")
}
func (UnimplementedModelServiceServer) UpsertSetting(context.Context, *UpsertSettingRequest) (*SettingInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertSetting not implemented")
}
func (UnimplementedModelServiceServer) DeleteSetting(context.Context, *DeleteSettingRequest) (*DeleteSettingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSetting not implemented")
}
func (UnimplementedModelServiceServer) mustEmbedUnimplementedModelServiceServer() {}
func (UnimplementedModelServiceServer) testEmbeddedByValue()                      {}

// UnsafeModelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModelServiceServer will
// result in compilation errors.
type UnsafeModelServiceServer interface {
	mustEmbedUnimplementedModelServiceServer()
}

func RegisterModelServiceServer(s grpc.ServiceRegistrar, srv ModelServiceServer) {
	// If the following call panics, it indicates UnimplementedModelServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModelService_ServiceDesc, srv)
}

func _ModelService_ListProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProvidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).ListProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelService_ListProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).ListProviders(ctx, req.(*ListProvidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_CreateProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).CreateProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelService_CreateProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).CreateProvider(ctx, req.(*CreateProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_UpdateProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).UpdateProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelService_UpdateProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).UpdateProvider(ctx, req.(*UpdateProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_DeleteProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).DeleteProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelService_DeleteProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).DeleteProvider(ctx, req.(*DeleteProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_SetProviderActive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetProviderActiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).SetProviderActive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelService_SetProviderActive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).SetProviderActive(ctx, req.(*SetProviderActiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelService_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_CreateModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).CreateModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelService_CreateModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).CreateModel(ctx, req.(*CreateModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_UpdateModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).UpdateModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelService_UpdateModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).UpdateModel(ctx, req.(*UpdateModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_DeleteModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).DeleteModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelService_DeleteModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).DeleteModel(ctx, req.(*DeleteModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_SetModelActive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetModelActiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).SetModelActive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelService_SetModelActive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).SetModelActive(ctx, req.(*SetModelActiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_ListUserProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserProvidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).ListUserProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelService_ListUserProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).ListUserProviders(ctx, req.(*ListUserProvidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_CreateUserProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).CreateUserProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelService_CreateUserProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).CreateUserProvider(ctx, req.(*CreateUserProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_UpdateUserProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).UpdateUserProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelService_UpdateUserProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).UpdateUserProvider(ctx, req.(*UpdateUserProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_DeleteUserProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).DeleteUserProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelService_DeleteUserProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).DeleteUserProvider(ctx, req.(*DeleteUserProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_ListUserModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).ListUserModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelService_ListUserModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).ListUserModels(ctx, req.(*ListUserModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_CreateUserModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).CreateUserModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelService_CreateUserModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).CreateUserModel(ctx, req.(*CreateUserModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_UpdateUserModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).UpdateUserModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelService_UpdateUserModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).UpdateUserModel(ctx, req.(*UpdateUserModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_DeleteUserModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).DeleteUserModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelService_DeleteUserModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).DeleteUserModel(ctx, req.(*DeleteUserModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_ListAvailableModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAvailableModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).ListAvailableModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelService_ListAvailableModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).ListAvailableModels(ctx, req.(*ListAvailableModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_ListSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).ListSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelService_ListSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).ListSettings(ctx, req.(*ListSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_GetSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).GetSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelService_GetSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).GetSetting(ctx, req.(*GetSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_UpsertSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).UpsertSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelService_UpsertSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).UpsertSetting(ctx, req.(*UpsertSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_DeleteSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).DeleteSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelService_DeleteSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).DeleteSetting(ctx, req.(*DeleteSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ModelService_ServiceDesc is the grpc.ServiceDesc for ModelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "model.ModelService",
	HandlerType: (*ModelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListProviders",
			Handler:    _ModelService_ListProviders_Handler,
		},
		{
			MethodName: "CreateProvider",
			Handler:    _ModelService_CreateProvider_Handler,
		},
		{
			MethodName: "UpdateProvider",
			Handler:    _ModelService_UpdateProvider_Handler,
		},
		{
			MethodName: "DeleteProvider",
			Handler:    _ModelService_DeleteProvider_Handler,
		},
		{
			MethodName: "SetProviderActive",
			Handler:    _ModelService_SetProviderActive_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _ModelService_ListModels_Handler,
		},
		{
			MethodName: "CreateModel",
			Handler:    _ModelService_CreateModel_Handler,
		},
		{
			MethodName: "UpdateModel",
			Handler:    _ModelService_UpdateModel_Handler,
		},
		{
			MethodName: "DeleteModel",
			Handler:    _ModelService_DeleteModel_Handler,
		},
		{
			MethodName: "SetModelActive",
			Handler:    _ModelService_SetModelActive_Handler,
		},
		{
			MethodName: "ListUserProviders",
			Handler:    _ModelService_ListUserProviders_Handler,
		},
		{
			MethodName: "CreateUserProvider",
			Handler:    _ModelService_CreateUserProvider_Handler,
		},
		{
			MethodName: "UpdateUserProvider",
			Handler:    _ModelService_UpdateUserProvider_Handler,
		},
		{
			MethodName: "DeleteUserProvider",
			Handler:    _ModelService_DeleteUserProvider_Handler,
		},
		{
			MethodName: "ListUserModels",
			Handler:    _ModelService_ListUserModels_Handler,
		},
		{
			MethodName: "CreateUserModel",
			Handler:    _ModelService_CreateUserModel_Handler,
		},
		{
			MethodName: "UpdateUserModel",
			Handler:    _ModelService_UpdateUserModel_Handler,
		},
		{
			MethodName: "DeleteUserModel",
			Handler:    _ModelService_DeleteUserModel_Handler,
		},
		{
			MethodName: "ListAvailableModels",
			Handler:    _ModelService_ListAvailableModels_Handler,
		},
		{
			MethodName: "ListSettings",
			Handler:    _ModelService_ListSettings_Handler,
		},
		{
			MethodName: "GetSetting",
			Handler:    _ModelService_GetSetting_Handler,
		},
		{
			MethodName: "UpsertSetting",
			Handler:    _ModelService_UpsertSetting_Handler,
		},
		{
			MethodName: "DeleteSetting",
			Handler:    _ModelService_DeleteSetting_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/model/model.proto",
}
