apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
{{- range $key, $value := .Values.userService.secret }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
