apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.postgres.service.type }}
  selector:
    app.kubernetes.io/name: postgres
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: 5432
      {{- if .Values.postgres.service.nodePort }}
      nodePort: {{ .Values.postgres.service.nodePort }}
      {{- end }}
