apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.ollama.service.type }}
  selector:
    app.kubernetes.io/name: ollama
  ports:
    - name: ollama
      port: {{ .Values.ollama.service.port }}
      targetPort: 11434
