apiGateway:
  secret:
    JWT_SECRET: change-me-in-prod

userService:
  secret:
    DB_USER: admin
    DB_PASSWORD: change-me
    REDIS_PASSWORD: change-me
    JWT_SECRET: change-me-in-prod

crawl4aiService:
  secret:
    API_KEY: change-me
