apiVersion: v1
kind: Secret
metadata:
  name: searxng
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  SEARXNG_SECRET: {{ required "searxng.secretKey is required" .Values.searxng.secretKey | quote }}
