// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: proto/crawl/crawl.proto
//
// 注：本仓库环境无 protoc 二进制，故 rawDesc 由 crawl_descriptor.go 在包初始化时
// 通过 FileDescriptorProto 构造并序列化得到，与 protoc 生成结果等价、可正常序列化。

package crawlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_crawl_crawl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}
func (x *HealthRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*HealthRequest) ProtoMessage()    {}
func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crawl_crawl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSeconds float32                `protobuf:"fixed32,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	AuthEnabled   bool                   `protobuf:"varint,5,opt,name=auth_enabled,json=authEnabled,proto3" json:"auth_enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_crawl_crawl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}
func (x *HealthResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*HealthResponse) ProtoMessage()    {}
func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crawl_crawl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type CrawlerOptions struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Timeout               int32                  `protobuf:"varint,1,opt,name=timeout,proto3" json:"timeout,omitempty"`
	UserAgent             string                 `protobuf:"bytes,2,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	BypassCache           bool                   `protobuf:"varint,3,opt,name=bypass_cache,json=bypassCache,proto3" json:"bypass_cache,omitempty"`
	RemoveOverlayElements bool                   `protobuf:"varint,4,opt,name=remove_overlay_elements,json=removeOverlayElements,proto3" json:"remove_overlay_elements,omitempty"`
	SimulateUser          bool                   `protobuf:"varint,5,opt,name=simulate_user,json=simulateUser,proto3" json:"simulate_user,omitempty"`
	Magic                 bool                   `protobuf:"varint,6,opt,name=magic,proto3" json:"magic,omitempty"`
	Locale                string                 `protobuf:"bytes,7,opt,name=locale,proto3" json:"locale,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CrawlerOptions) Reset() {
	*x = CrawlerOptions{}
	mi := &file_proto_crawl_crawl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}
func (x *CrawlerOptions) String() string { return protoimpl.X.MessageStringOf(x) }
func (*CrawlerOptions) ProtoMessage()     {}
func (x *CrawlerOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crawl_crawl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type LLMConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ApiKey         string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	BaseUrl        string                 `protobuf:"bytes,2,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	Model          string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Temperature    float32                `protobuf:"fixed32,4,opt,name=temperature,proto3" json:"temperature,omitempty"`
	MaxTokens      int32                  `protobuf:"varint,5,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	RequestTimeout int32                  `protobuf:"varint,6,opt,name=request_timeout,json=requestTimeout,proto3" json:"request_timeout,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LLMConfig) Reset() {
	*x = LLMConfig{}
	mi := &file_proto_crawl_crawl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}
func (x *LLMConfig) String() string { return protoimpl.X.MessageStringOf(x) }
func (*LLMConfig) ProtoMessage()    {}
func (x *LLMConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crawl_crawl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ExtractSchemaField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Required      bool                   `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	ItemsJson     string                 `protobuf:"bytes,5,opt,name=items_json,json=itemsJson,proto3" json:"items_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractSchemaField) Reset() {
	*x = ExtractSchemaField{}
	mi := &file_proto_crawl_crawl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}
func (x *ExtractSchemaField) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ExtractSchemaField) ProtoMessage()     {}
func (x *ExtractSchemaField) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crawl_crawl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type CrawlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Options       *CrawlerOptions        `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	WaitFor       string                 `protobuf:"bytes,3,opt,name=wait_for,json=waitFor,proto3" json:"wait_for,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrawlRequest) Reset() {
	*x = CrawlRequest{}
	mi := &file_proto_crawl_crawl_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}
func (x *CrawlRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*CrawlRequest) ProtoMessage()    {}
func (x *CrawlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crawl_crawl_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type CrawlResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Url            string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Markdown       string                 `protobuf:"bytes,3,opt,name=markdown,proto3" json:"markdown,omitempty"`
	StatusCode     int32                  `protobuf:"varint,4,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ErrorCode      string                 `protobuf:"bytes,5,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ErrorRetryable bool                   `protobuf:"varint,7,opt,name=error_retryable,json=errorRetryable,proto3" json:"error_retryable,omitempty"`
	ElapsedMs      int32                  `protobuf:"varint,8,opt,name=elapsed_ms,json=elapsedMs,proto3" json:"elapsed_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CrawlResponse) Reset() {
	*x = CrawlResponse{}
	mi := &file_proto_crawl_crawl_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}
func (x *CrawlResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*CrawlResponse) ProtoMessage()    {}
func (x *CrawlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crawl_crawl_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ExtractRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Url               string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Instruction       string                 `protobuf:"bytes,2,opt,name=instruction,proto3" json:"instruction,omitempty"`
	SchemaFields      []*ExtractSchemaField  `protobuf:"bytes,3,rep,name=schema_fields,json=schemaFields,proto3" json:"schema_fields,omitempty"`
	Llm               *LLMConfig             `protobuf:"bytes,4,opt,name=llm,proto3" json:"llm,omitempty"`
	Options           *CrawlerOptions        `protobuf:"bytes,5,opt,name=options,proto3" json:"options,omitempty"`
	ExtractionTimeout int32                  `protobuf:"varint,6,opt,name=extraction_timeout,json=extractionTimeout,proto3" json:"extraction_timeout,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExtractRequest) Reset() {
	*x = ExtractRequest{}
	mi := &file_proto_crawl_crawl_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}
func (x *ExtractRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ExtractRequest) ProtoMessage()    {}
func (x *ExtractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crawl_crawl_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ExtractResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Url            string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Markdown       string                 `protobuf:"bytes,3,opt,name=markdown,proto3" json:"markdown,omitempty"`
	DataJson       string                 `protobuf:"bytes,4,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	ErrorCode      string                 `protobuf:"bytes,5,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ErrorRetryable bool                   `protobuf:"varint,7,opt,name=error_retryable,json=errorRetryable,proto3" json:"error_retryable,omitempty"`
	ElapsedMs      int32                  `protobuf:"varint,8,opt,name=elapsed_ms,json=elapsedMs,proto3" json:"elapsed_ms,omitempty"`
	Model          string                 `protobuf:"bytes,9,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExtractResponse) Reset() {
	*x = ExtractResponse{}
	mi := &file_proto_crawl_crawl_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}
func (x *ExtractResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ExtractResponse) ProtoMessage()    {}
func (x *ExtractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crawl_crawl_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// ---- Getters ----

func (x *HealthResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}
func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}
func (x *HealthResponse) GetUptimeSeconds() float32 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}
func (x *HealthResponse) GetAuthEnabled() bool {
	if x != nil {
		return x.AuthEnabled
	}
	return false
}

func (x *CrawlerOptions) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}
func (x *CrawlerOptions) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}
func (x *CrawlerOptions) GetBypassCache() bool {
	if x != nil {
		return x.BypassCache
	}
	return false
}
func (x *CrawlerOptions) GetRemoveOverlayElements() bool {
	if x != nil {
		return x.RemoveOverlayElements
	}
	return false
}
func (x *CrawlerOptions) GetSimulateUser() bool {
	if x != nil {
		return x.SimulateUser
	}
	return false
}
func (x *CrawlerOptions) GetMagic() bool {
	if x != nil {
		return x.Magic
	}
	return false
}
func (x *CrawlerOptions) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *LLMConfig) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}
func (x *LLMConfig) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}
func (x *LLMConfig) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}
func (x *LLMConfig) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}
func (x *LLMConfig) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}
func (x *LLMConfig) GetRequestTimeout() int32 {
	if x != nil {
		return x.RequestTimeout
	}
	return 0
}

func (x *ExtractSchemaField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}
func (x *ExtractSchemaField) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}
func (x *ExtractSchemaField) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}
func (x *ExtractSchemaField) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}
func (x *ExtractSchemaField) GetItemsJson() string {
	if x != nil {
		return x.ItemsJson
	}
	return ""
}

func (x *CrawlRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}
func (x *CrawlRequest) GetOptions() *CrawlerOptions {
	if x != nil {
		return x.Options
	}
	return nil
}
func (x *CrawlRequest) GetWaitFor() string {
	if x != nil {
		return x.WaitFor
	}
	return ""
}

func (x *CrawlResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}
func (x *CrawlResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}
func (x *CrawlResponse) GetMarkdown() string {
	if x != nil {
		return x.Markdown
	}
	return ""
}
func (x *CrawlResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}
func (x *CrawlResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}
func (x *CrawlResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}
func (x *CrawlResponse) GetErrorRetryable() bool {
	if x != nil {
		return x.ErrorRetryable
	}
	return false
}
func (x *CrawlResponse) GetElapsedMs() int32 {
	if x != nil {
		return x.ElapsedMs
	}
	return 0
}

func (x *ExtractRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}
func (x *ExtractRequest) GetInstruction() string {
	if x != nil {
		return x.Instruction
	}
	return ""
}
func (x *ExtractRequest) GetSchemaFields() []*ExtractSchemaField {
	if x != nil {
		return x.SchemaFields
	}
	return nil
}
func (x *ExtractRequest) GetLlm() *LLMConfig {
	if x != nil {
		return x.Llm
	}
	return nil
}
func (x *ExtractRequest) GetOptions() *CrawlerOptions {
	if x != nil {
		return x.Options
	}
	return nil
}
func (x *ExtractRequest) GetExtractionTimeout() int32 {
	if x != nil {
		return x.ExtractionTimeout
	}
	return 0
}

func (x *ExtractResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}
func (x *ExtractResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}
func (x *ExtractResponse) GetMarkdown() string {
	if x != nil {
		return x.Markdown
	}
	return ""
}
func (x *ExtractResponse) GetDataJson() string {
	if x != nil {
		return x.DataJson
	}
	return ""
}
func (x *ExtractResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}
func (x *ExtractResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}
func (x *ExtractResponse) GetErrorRetryable() bool {
	if x != nil {
		return x.ErrorRetryable
	}
	return false
}
func (x *ExtractResponse) GetElapsedMs() int32 {
	if x != nil {
		return x.ElapsedMs
	}
	return 0
}
func (x *ExtractResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

var file_proto_crawl_crawl_proto_rawDesc = mustMarshalCrawlFile()

var file_proto_crawl_crawl_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_crawl_crawl_proto_goTypes = []any{
	(*HealthRequest)(nil),      // 0
	(*HealthResponse)(nil),     // 1
	(*CrawlerOptions)(nil),     // 2
	(*LLMConfig)(nil),          // 3
	(*ExtractSchemaField)(nil), // 4
	(*CrawlRequest)(nil),       // 5
	(*CrawlResponse)(nil),      // 6
	(*ExtractRequest)(nil),    // 7
	(*ExtractResponse)(nil),   // 8
}
// 消息类型交叉引用索引。编码方式（与 protoc 生成一致）：
//   depIdxs.Get(i,j) = x[x[len(x)-i-1]+j]
// 即最后 n 个条目是偏移量（每条消息一个，偏移值指向 data 区的起始下标），
// 前段是各消息类型字段所引用 Go 类型在 goTypes 中的下标（按消息声明顺序）。
//   - CrawlRequest.options -> CrawlerOptions(2)
//   - ExtractRequest.schema_fields -> ExtractSchemaField(4)
//   - ExtractRequest.llm -> LLMConfig(3)
//   - ExtractRequest.options -> CrawlerOptions(2)
var file_proto_crawl_crawl_proto_depIdxs = []int32{
	// data 区
	2, 4, 3, 2,
	// 偏移量区（共 9 条消息，off_i 存于 x[len-1-i]）
	4, // i=8 ExtractResponse 起始
	1, // i=7 ExtractRequest 起始
	1, // i=6 CrawlResponse 起始
	0, // i=5 CrawlRequest 起始
	0, // i=4 ExtractSchemaField 起始
	0, // i=3 LLMConfig 起始
	0, // i=2 CrawlerOptions 起始
	0, // i=1 HealthResponse 起始
	0, // i=0 HealthRequest 起始
}

func init() {
	for i := range file_proto_crawl_crawl_proto_msgTypes {
		file_proto_crawl_crawl_proto_msgTypes[i].Exporter = func(v any, i int) any {
			switch m := v.(type) {
			case *HealthRequest:
				return &m.state
			case *HealthResponse:
				return &m.state
			case *CrawlerOptions:
				return &m.state
			case *LLMConfig:
				return &m.state
			case *ExtractSchemaField:
				return &m.state
			case *CrawlRequest:
				return &m.state
			case *CrawlResponse:
				return &m.state
			case *ExtractRequest:
				return &m.state
			case *ExtractResponse:
				return &m.state
			}
			return nil
		}
	}
}

func file_proto_crawl_crawl_proto_init() {
	if File_proto_crawl_crawl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_crawl_crawl_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_crawl_crawl_proto_goTypes,
		DependencyIndexes: file_proto_crawl_crawl_proto_depIdxs,
		MessageInfos:      file_proto_crawl_crawl_proto_msgTypes,
	}.Build()
	File_proto_crawl_crawl_proto = out.File
	file_proto_crawl_crawl_proto_goTypes = nil
	file_proto_crawl_crawl_proto_depIdxs = nil
}

var File_proto_crawl_crawl_proto protoreflect.FileDescriptor

func init() { file_proto_crawl_crawl_proto_init() }
