// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: proto/crawl/crawl.proto

package crawlpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CrawlService_Health_FullMethodName  = "/crawl.CrawlService/Health"
	CrawlService_Crawl_FullMethodName   = "/crawl.CrawlService/Crawl"
	CrawlService_Extract_FullMethodName = "/crawl.CrawlService/Extract"
)

// CrawlServiceClient is the client API for CrawlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CrawlService 智能网页抓取与结构化抽取服务（gRPC 版）。
//
// 语义对齐原 FastAPI 版本的 /crawl、/extract、/health 三个接口，
// 底层依旧使用 Python 的 Crawl4AI 库（浏览器渲染 + Markdown 清洗 + LLM 抽取），
// 仅把传输层从 HTTP/JSON 换成 gRPC。
type CrawlServiceClient interface {
	// Health 存活探针，对应原 /health。
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// Crawl 抓取单个 URL 并返回清洗后的 Markdown（不调用 LLM），对应原 /crawl。
	Crawl(ctx context.Context, in *CrawlRequest, opts ...grpc.CallOption) (*CrawlResponse, error)
	// Extract 抓取单个 URL 并基于 LLM 抽取结构化数据，对应原 /extract。
	Extract(ctx context.Context, in *ExtractRequest, opts ...grpc.CallOption) (*ExtractResponse, error)
}

type crawlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCrawlServiceClient(cc grpc.ClientConnInterface) CrawlServiceClient {
	return &crawlServiceClient{cc}
}

func (c *crawlServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, CrawlService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crawlServiceClient) Crawl(ctx context.Context, in *CrawlRequest, opts ...grpc.CallOption) (*CrawlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CrawlResponse)
	err := c.cc.Invoke(ctx, CrawlService_Crawl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crawlServiceClient) Extract(ctx context.Context, in *ExtractRequest, opts ...grpc.CallOption) (*ExtractResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtractResponse)
	err := c.cc.Invoke(ctx, CrawlService_Extract_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CrawlServiceServer is the server API for CrawlService service.
// All implementations must embed UnimplementedCrawlServiceServer
// for forward compatibility.
//
// CrawlService 智能网页抓取与结构化抽取服务（gRPC 版）。
//
// 语义对齐原 FastAPI 版本的 /crawl、/extract、/health 三个接口，
// 底层依旧使用 Python 的 Crawl4AI 库（浏览器渲染 + Markdown 清洗 + LLM 抽取），
// 仅把传输层从 HTTP/JSON 换成 gRPC。
type CrawlServiceServer interface {
	// Health 存活探针，对应原 /health。
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// Crawl 抓取单个 URL 并返回清洗后的 Markdown（不调用 LLM），对应原 /crawl。
	Crawl(context.Context, *CrawlRequest) (*CrawlResponse, error)
	// Extract 抓取单个 URL 并基于 LLM 抽取结构化数据，对应原 /extract。
	Extract(context.Context, *ExtractRequest) (*ExtractResponse, error)
	mustEmbedUnimplementedCrawlServiceServer()
}

// UnimplementedCrawlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCrawlServiceServer struct{}

func (UnimplementedCrawlServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedCrawlServiceServer) Crawl(context.Context, *CrawlRequest) (*CrawlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Crawl not implemented")
}
func (UnimplementedCrawlServiceServer) Extract(context.Context, *ExtractRequest) (*ExtractResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Extract not implemented")
}
func (UnimplementedCrawlServiceServer) mustEmbedUnimplementedCrawlServiceServer() {}
func (UnimplementedCrawlServiceServer) testEmbeddedByValue()                      {}

// UnsafeCrawlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CrawlServiceServer will
// result in compilation errors.
type UnsafeCrawlServiceServer interface {
	mustEmbedUnimplementedCrawlServiceServer()
}

func RegisterCrawlServiceServer(s grpc.ServiceRegistrar, srv CrawlServiceServer) {
	// If the following call panics, it indicates UnimplementedCrawlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CrawlService_ServiceDesc, srv)
}

func _CrawlService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrawlServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrawlService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrawlServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrawlService_Crawl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrawlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrawlServiceServer).Crawl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrawlService_Crawl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrawlServiceServer).Crawl(ctx, req.(*CrawlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrawlService_Extract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrawlServiceServer).Extract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrawlService_Extract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrawlServiceServer).Extract(ctx, req.(*ExtractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CrawlService_ServiceDesc is the grpc.ServiceDesc for CrawlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CrawlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "crawl.CrawlService",
	HandlerType: (*CrawlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _CrawlService_Health_Handler,
		},
		{
			MethodName: "Crawl",
			Handler:    _CrawlService_Crawl_Handler,
		},
		{
			MethodName: "Extract",
			Handler:    _CrawlService_Extract_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/crawl/crawl.proto",
}
