// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// 	protoc-gen-go-grpc v1.5.1
// 	protoc             v5.29.3
// source: proto/crawl/crawl.proto

package crawlpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const _ = grpc.SupportPackageIsVersion9

// CrawlServiceClient is the client API for CrawlService service.
type CrawlServiceClient interface {
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	Crawl(ctx context.Context, in *CrawlRequest, opts ...grpc.CallOption) (*CrawlResponse, error)
	Extract(ctx context.Context, in *ExtractRequest, opts ...grpc.CallOption) (*ExtractResponse, error)
}

type crawlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCrawlServiceClient(cc grpc.ClientConnInterface) CrawlServiceClient {
	return &crawlServiceClient{cc}
}

func (c *crawlServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/crawl.CrawlService/Health", in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crawlServiceClient) Crawl(ctx context.Context, in *CrawlRequest, opts ...grpc.CallOption) (*CrawlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CrawlResponse)
	err := c.cc.Invoke(ctx, "/crawl.CrawlService/Crawl", in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crawlServiceClient) Extract(ctx context.Context, in *ExtractRequest, opts ...grpc.CallOption) (*ExtractResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtractResponse)
	err := c.cc.Invoke(ctx, "/crawl.CrawlService/Extract", in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CrawlServiceServer is the server API for CrawlService service.
type CrawlServiceServer interface {
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	Crawl(context.Context, *CrawlRequest) (*CrawlResponse, error)
	Extract(context.Context, *ExtractRequest) (*ExtractResponse, error)
	mustEmbedUnimplementedCrawlServiceServer()
}

type UnimplementedCrawlServiceServer struct{}

func (UnimplementedCrawlServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedCrawlServiceServer) Crawl(context.Context, *CrawlRequest) (*CrawlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Crawl not implemented")
}
func (UnimplementedCrawlServiceServer) Extract(context.Context, *ExtractRequest) (*ExtractResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Extract not implemented")
}
func (UnimplementedCrawlServiceServer) mustEmbedUnimplementedCrawlServiceServer() {}

type UnsafeCrawlServiceServer interface {
	mustEmbedUnimplementedCrawlServiceServer()
}

func RegisterCrawlServiceServer(s grpc.ServiceRegistrar, srv CrawlServiceServer) {
	s.RegisterService(&CrawlService_ServiceDesc, srv)
}

func _CrawlService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrawlServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/crawl.CrawlService/Health"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrawlServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrawlService_Crawl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrawlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrawlServiceServer).Crawl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/crawl.CrawlService/Crawl"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrawlServiceServer).Crawl(ctx, req.(*CrawlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrawlService_Extract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrawlServiceServer).Extract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/crawl.CrawlService/Extract"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrawlServiceServer).Extract(ctx, req.(*ExtractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var CrawlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "crawl.CrawlService",
	HandlerType: (*CrawlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "Health", Handler: _CrawlService_Health_Handler},
		{MethodName: "Crawl", Handler: _CrawlService_Crawl_Handler},
		{MethodName: "Extract", Handler: _CrawlService_Extract_Handler},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/crawl/crawl.proto",
}
